Buildspec: Convert to multiline

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -17,15 +17,18 @@ phases:
   build:
     on-failure: ABORT
     commands:
-      - APP_VERSION=$( echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d '/' -f 3 )
-      - echo "Building the Docker image for Python Cowsay version ${APP_VERSION}..."
-      - docker build -t $IMAGE_NAME:$APP_VERSION .
-      - docker images $IMAGE_NAME:$APP_VERSION
+      - |
+echo "Parsing HEAD_REF: $CODEBUILD_WEBHOOK_HEAD_REF"
+APP_VERSION=$( echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d '/' -f 3 )
+echo "Building the Docker image for Python Cowsay version ${APP_VERSION}..."
+docker build -t $IMAGE_NAME:$APP_VERSION .
+docker images $IMAGE_NAME:$APP_VERSION
   
   post_build:
     on-failure: ABORT
     commands:
-      - APP_VERSION=$( echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d '/' -f 3 )
-      - echo "Pushing image to Lightsail container service..."
-      - aws lightsail push-container-image --region $AWS_REGION --service-name $LIGHTSAIL_SERVICE_NAME --label $IMAGE_NAME --image $IMAGE_NAME:$APP_VERSION || echo "FAILS"
+      - |
+APP_VERSION=$( echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d '/' -f 3 )
+echo "Pushing image to Lightsail container service..."
+aws lightsail push-container-image --region $AWS_REGION --service-name $LIGHTSAIL_SERVICE_NAME --label $IMAGE_NAME --image $IMAGE_NAME:$APP_VERSION || echo "FAILS"
       
